# Generated by Django 3.2 on 2021-04-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shucks', '0003_auto_20210424_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='image',
            field=models.ImageField(upload_to='static/images_ad'),
        ),
    ]
