# Generated by Django 3.2 on 2021-04-26 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shucks', '0005_auto_20210425_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='description',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=500)),
                ('save_info', models.BooleanField(default=False)),
                ('use_default', models.BooleanField(default=False)),
                ('payment_option', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
