# Generated by Django 3.2 on 2021-04-27 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shucks', '0007_address_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='payment_option',
        ),
    ]
