# Generated by Django 3.2 on 2021-04-27 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shucks', '0010_alter_address_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='new_price',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='discount',
            new_name='old_price',
        ),
    ]
