# Generated by Django 3.2 on 2021-04-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shucks', '0011_auto_20210427_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=1400, max_digits=7),
            preserve_default=False,
        ),
    ]
