# Generated by Django 3.2 on 2021-04-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shucks', '0013_alter_item_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='best_seller',
            field=models.BooleanField(default=False),
        ),
    ]
