# Generated by Django 3.2 on 2021-04-30 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shucks', '0016_auto_20210429_1554'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advert',
        ),
    ]
